#ifndef CECS_PLATFORM_H
#define CECS_PLATFORM_H

#ifndef CECS_PLATFORM_MASK
#ifdef CECS_PLATFORM
#error "CECS_PLATFORM_MASK is not defined, but CECS_PLATFORM is defined. Please define CECS_PLATFORM_MASK to the appropriate value for your platform."
#endif


#ifndef CECS_PLATFORM_MASK_NONE
#define CECS_PLATFORM_MASK_NONE 0x00
#endif
#ifndef CECS_PLATFORM_MASK_X86_64
#define CECS_PLATFORM_MASK_X86_64 0x01
#endif
#ifndef CECS_PLATFORM_MASK_X86_32
#define CECS_PLATFORM_MASK_X86_32 0x02
#endif
#ifndef CECS_PLATFORM_MASK_ARM2
#define CECS_PLATFORM_MASK_ARM2 0x04
#endif
#ifndef CECS_PLATFORM_MASK_ARM3
#define CECS_PLATFORM_MASK_ARM3 0x08
#endif
#ifndef CECS_PLATFORM_MASK_ARM4T
#define CECS_PLATFORM_MASK_ARM4T 0x10
#endif
#ifndef CECS_PLATFORM_MASK_ARM5
#define CECS_PLATFORM_MASK_ARM5 0x20
#endif
#ifndef CECS_PLATFORM_MASK_ARM6T2
#define CECS_PLATFORM_MASK_ARM6T2 0x40
#endif
#ifndef CECS_PLATFORM_MASK_ARM6
#define CECS_PLATFORM_MASK_ARM6 0x80
#endif
#ifndef CECS_PLATFORM_MASK_ARM7
#define CECS_PLATFORM_MASK_ARM7 0x100
#endif
#ifndef CECS_PLATFORM_MASK_ARM7A
#define CECS_PLATFORM_MASK_ARM7A 0x200
#endif
#ifndef CECS_PLATFORM_MASK_ARM7R
#define CECS_PLATFORM_MASK_ARM7R 0x400
#endif
#ifndef CECS_PLATFORM_MASK_ARM7M
#define CECS_PLATFORM_MASK_ARM7M 0x800
#endif
#ifndef CECS_PLATFORM_MASK_ARM7S
#define CECS_PLATFORM_MASK_ARM7S 0x1000
#endif
#ifndef CECS_PLATFORM_MASK_ARM64
#define CECS_PLATFORM_MASK_ARM64 0x2000
#endif
#ifndef CECS_PLATFORM_MASK_MIPS
#define CECS_PLATFORM_MASK_MIPS 0x4000
#endif
#ifndef CECS_PLATFORM_MASK_SUPERH
#define CECS_PLATFORM_MASK_SUPERH 0x8000
#endif
#ifndef CECS_PLATFORM_MASK_POWERPC
#define CECS_PLATFORM_MASK_POWERPC 0x10000
#endif
#ifndef CECS_PLATFORM_MASK_POWERPC64
#define CECS_PLATFORM_MASK_POWERPC64 0x20000
#endif
#ifndef CECS_PLATFORM_MASK_SPARC
#define CECS_PLATFORM_MASK_SPARC 0x40000
#endif
#ifndef CECS_PLATFORM_MASK_M68K
#define CECS_PLATFORM_MASK_M68K 0x80000
#endif


// Source - https://stackoverflow.com/a/66249936
// Posted by FreakAnon, modified by community. See post 'Timeline' for change history
// Retrieved 2026-06-04, License - CC BY-SA 4.0
#ifndef CECS_PLATFORM_X86_64
#if defined(__x86_64__) || defined(_M_X64) || defined(__amd64__)
#define CECS_PLATFORM_X86_64 CECS_PLATFORM_MASK_X86_64
#else
#define CECS_PLATFORM_X86_64 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_X86_32
#if defined(i386) || defined(__i386__) || defined(__i386) || defined(_M_IX86)
#define CECS_PLATFORM_X86_32 CECS_PLATFORM_MASK_X86_32
#else
#define CECS_PLATFORM_X86_32 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM2
#if defined(__ARM_ARCH_2__)
#define CECS_PLATFORM_ARM2 CECS_PLATFORM_MASK_ARM2
#else
#define CECS_PLATFORM_ARM2 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM3
#if defined(__ARM_ARCH_3__) || defined(__ARM_ARCH_3M__)
#define CECS_PLATFORM_ARM3 CECS_PLATFORM_MASK_ARM3
#else
#define CECS_PLATFORM_ARM3 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM4T
#if defined(__ARM_ARCH_4T__) || defined(__TARGET_ARM_4T)
#define CECS_PLATFORM_ARM4T CECS_PLATFORM_MASK_ARM4T
#else
#define CECS_PLATFORM_ARM4T CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM5
#if defined(__ARM_ARCH_5__) || defined(__ARM_ARCH_5E__)
#define CECS_PLATFORM_ARM5 CECS_PLATFORM_MASK_ARM5
#else
#define CECS_PLATFORM_ARM5 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM6T2
#if defined(__ARM_ARCH_6T2__)
#define CECS_PLATFORM_ARM6T2 CECS_PLATFORM_MASK_ARM6T2
#else
#define CECS_PLATFORM_ARM6T2 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM6
#if defined(__ARM_ARCH_6__) || defined(__ARM_ARCH_6J__) || defined(__ARM_ARCH_6K__) || defined(__ARM_ARCH_6Z__) || defined(__ARM_ARCH_6ZK__)
#define CECS_PLATFORM_ARM6 CECS_PLATFORM_MASK_ARM6
#else
#define CECS_PLATFORM_ARM6 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM7
#if defined(__ARM_ARCH_7__) || defined(__ARM_ARCH_7A__) || defined(__ARM_ARCH_7R__) || defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7S__)
#define CECS_PLATFORM_ARM7 CECS_PLATFORM_MASK_ARM7
#else
#define CECS_PLATFORM_ARM7 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM7A
#if defined(__ARM_ARCH_7A__)
#define CECS_PLATFORM_ARM7A CECS_PLATFORM_MASK_ARM7A
#else
#define CECS_PLATFORM_ARM7A CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM7R
#if defined(__ARM_ARCH_7R__)
#define CECS_PLATFORM_ARM7R CECS_PLATFORM_MASK_ARM7R
#else
#define CECS_PLATFORM_ARM7R CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM7M
#if defined(__ARM_ARCH_7M__)
#define CECS_PLATFORM_ARM7M CECS_PLATFORM_MASK_ARM7M
#else
#define CECS_PLATFORM_ARM7M CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM7S
#if defined(__ARM_ARCH_7S__)
#define CECS_PLATFORM_ARM7S CECS_PLATFORM_MASK_ARM7S
#else
#define CECS_PLATFORM_ARM7S CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_ARM64
#if defined(__aarch64__) || defined(_M_ARM64) || defined(__arm64__)
#define CECS_PLATFORM_ARM64 CECS_PLATFORM_MASK_ARM64
#else
#define CECS_PLATFORM_ARM64 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_MIPS
#if defined(mips) || defined(__mips__) || defined(__mips)
#define CECS_PLATFORM_MIPS CECS_PLATFORM_MASK_MIPS
#else
#define CECS_PLATFORM_MIPS CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_SUPERH
#if defined(__sh__)
#define CECS_PLATFORM_SUPERH CECS_PLATFORM_MASK_SUPERH
#else
#define CECS_PLATFORM_SUPERH CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_POWERPC
#if defined(__powerpc) || defined(__powerpc__) || defined(__POWERPC__) || defined(__ppc__) || defined(__PPC__) || defined(_ARCH_PPC)
#define CECS_PLATFORM_POWERPC CECS_PLATFORM_MASK_POWERPC
#else
#define CECS_PLATFORM_POWERPC CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_POWERPC64
#if defined(__powerpc64__) || defined(__PPC64__) || defined(__ppc64__) || defined(_ARCH_PPC64)
#define CECS_PLATFORM_POWERPC64 CECS_PLATFORM_MASK_POWERPC64
#else
#define CECS_PLATFORM_POWERPC64 CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_SPARC
#if defined(__sparc__) || defined(__sparc)
#define CECS_PLATFORM_SPARC CECS_PLATFORM_MASK_SPARC
#else
#define CECS_PLATFORM_SPARC CECS_PLATFORM_MASK_NONE
#endif
#endif

#ifndef CECS_PLATFORM_M68K
#if defined(__m68k__)
#define CECS_PLATFORM_M68K CECS_PLATFORM_MASK_M68K
#else
#define CECS_PLATFORM_M68K CECS_PLATFORM_MASK_NONE
#endif
#endif


#define CECS_PLATFORM_MASK ( \
	CECS_PLATFORM_X86_64 \
	| CECS_PLATFORM_X86_32 \
	| CECS_PLATFORM_ARM2 \
	| CECS_PLATFORM_ARM3 \
	| CECS_PLATFORM_ARM4T \
	| CECS_PLATFORM_ARM5 \
	| CECS_PLATFORM_ARM6T2 \
	| CECS_PLATFORM_ARM6 \
	| CECS_PLATFORM_ARM7 \
	| CECS_PLATFORM_ARM7A \
	| CECS_PLATFORM_ARM7R \
	| CECS_PLATFORM_ARM7M \
	| CECS_PLATFORM_ARM7S \
	| CECS_PLATFORM_ARM64 \
	| CECS_PLATFORM_MIPS \
	| CECS_PLATFORM_SUPERH \
	| CECS_PLATFORM_POWERPC \
	| CECS_PLATFORM_POWERPC64 \
	| CECS_PLATFORM_SPARC \
	| CECS_PLATFORM_M68K \
)

#if CECS_PLATFORM_X86_64 == CECS_PLATFORM_MASK_X86_64
#define CECS_PLATFORM CECS_PLATFORM_MASK_X86_64
#elif CECS_PLATFORM_X86_32 == CECS_PLATFORM_MASK_X86_32
#define CECS_PLATFORM CECS_PLATFORM_MASK_X86_32
#elif CECS_PLATFORM_ARM2 == CECS_PLATFORM_MASK_ARM2
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM2
#elif CECS_PLATFORM_ARM3 == CECS_PLATFORM_MASK_ARM3
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM3
#elif CECS_PLATFORM_ARM4T == CECS_PLATFORM_MASK_ARM4T
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM4T
#elif CECS_PLATFORM_ARM5 == CECS_PLATFORM_MASK_ARM5
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM5
#elif CECS_PLATFORM_ARM6T2 == CECS_PLATFORM_MASK_ARM6T2
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM6T2
#elif CECS_PLATFORM_ARM6 == CECS_PLATFORM_MASK_ARM6
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM6
#elif CECS_PLATFORM_ARM7 == CECS_PLATFORM_MASK_ARM7
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM7
#elif CECS_PLATFORM_ARM7A == CECS_PLATFORM_MASK_ARM7A
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM7A
#elif CECS_PLATFORM_ARM7R == CECS_PLATFORM_MASK_ARM7R
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM7R
#elif CECS_PLATFORM_ARM7M == CECS_PLATFORM_MASK_ARM7M
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM7M
#elif CECS_PLATFORM_ARM7S == CECS_PLATFORM_MASK_ARM7S
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM7S
#elif CECS_PLATFORM_ARM64 == CECS_PLATFORM_MASK_ARM64
#define CECS_PLATFORM CECS_PLATFORM_MASK_ARM64
#elif CECS_PLATFORM_MIPS == CECS_PLATFORM_MASK_MIPS
#define CECS_PLATFORM CECS_PLATFORM_MASK_MIPS
#elif CECS_PLATFORM_SUPERH == CECS_PLATFORM_MASK_SUPERH
#define CECS_PLATFORM CECS_PLATFORM_MASK_SUPERH
#elif CECS_PLATFORM_POWERPC == CECS_PLATFORM_MASK_POWERPC
#define CECS_PLATFORM CECS_PLATFORM_MASK_POWERPC
#elif CECS_PLATFORM_POWERPC64 == CECS_PLATFORM_MASK_POWERPC64
#define CECS_PLATFORM CECS_PLATFORM_MASK_POWERPC64
#elif CECS_PLATFORM_SPARC == CECS_PLATFORM_MASK_SPARC
#define CECS_PLATFORM CECS_PLATFORM_MASK_SPARC
#elif CECS_PLATFORM_M68K == CECS_PLATFORM_MASK_M68K
#define CECS_PLATFORM CECS_PLATFORM_MASK_M68K
#else
#define CECS_PLATFORM CECS_PLATFORM_MASK_NONE
#endif


#if CECS_PLATFORM == CECS_PLATFORM_MASK_NONE
#error "unsupported platform, currently supported platforms are: x86_64, x86_32, ARM2, ARM3, ARM4T, ARM5, ARM6T2, ARM6, ARM7, ARM7A, ARM7R, ARM7M, ARM7S, ARM64, MIPS, SUPERH, POWERPC, POWERPC64, SPARC, M68K"
#endif

#ifndef CECS_PLATFORM_MASK_X86
#define CECS_PLATFORM_MASK_X86 (CECS_PLATFORM_MASK_X86_64 | CECS_PLATFORM_MASK_X86_32)
#endif
#ifndef CECS_PLATFORM_MASK_ARM
#define CECS_PLATFORM_MASK_ARM ( \
	CECS_PLATFORM_MASK_ARM2 \
	| CECS_PLATFORM_MASK_ARM3 \
	| CECS_PLATFORM_MASK_ARM4T \
	| CECS_PLATFORM_MASK_ARM5 \
	| CECS_PLATFORM_MASK_ARM6T2 \
	| CECS_PLATFORM_MASK_ARM6 \
	| CECS_PLATFORM_MASK_ARM7 \
	| CECS_PLATFORM_MASK_ARM7A \
	| CECS_PLATFORM_MASK_ARM7R \
	| CECS_PLATFORM_MASK_ARM7M \
	| CECS_PLATFORM_MASK_ARM7S \
	| CECS_PLATFORM_MASK_ARM64 \
)
#endif

#ifndef CECS_PLATFORM_MASK_POWERPC_FAMILY
#define CECS_PLATFORM_MASK_POWERPC_FAMILY (CECS_PLATFORM_MASK_POWERPC | CECS_PLATFORM_MASK_POWERPC64)
#endif


#ifndef CECS_PLATFORM_WORD_BITS_32
#define CECS_PLATFORM_WORD_BITS_32 32
#endif
#ifndef CECS_PLATFORM_WORD_BITS_64
#define CECS_PLATFORM_WORD_BITS_64 64
#endif

#ifndef CECS_PLATFORM_WORD_BITS
#ifdef CECS_PLATFORM_WORD_BITS_LOG2
#error "CECS_PLATFORM_WORD_BITS is not defined, but CECS_PLATFORM_WORD_BITS_LOG2 is defined. Please define CECS_PLATFORM_WORD_BITS to the appropriate value for your platform (e.g. CECS_PLATFORM_WORD_BITS_32 or CECS_PLATFORM_WORD_BITS_64)."
#endif

#if CECS_PLATFORM_MASK & (CECS_PLATFORM_MASK_X86_64 | CECS_PLATFORM_MASK_ARM64 | CECS_PLATFORM_MASK_POWERPC64)
#define CECS_PLATFORM_WORD_BITS CECS_PLATFORM_WORD_BITS_64
#define CECS_PLATFORM_WORD_BITS_LOG2 6

#elif CECS_PLATFORM_MASK & ( \
    CECS_PLATFORM_MASK_X86_32 \
	| CECS_PLATFORM_MASK_ARM2 \
	| CECS_PLATFORM_MASK_ARM3 \
	| CECS_PLATFORM_MASK_ARM4T \
	| CECS_PLATFORM_MASK_ARM5 \
	| CECS_PLATFORM_MASK_ARM6T2 \
	| CECS_PLATFORM_MASK_ARM6 \
	| CECS_PLATFORM_MASK_ARM7 \
	| CECS_PLATFORM_MASK_ARM7A \
	| CECS_PLATFORM_MASK_ARM7R \
	| CECS_PLATFORM_MASK_ARM7M \
	| CECS_PLATFORM_MASK_ARM7S \
	| CECS_PLATFORM_MASK_MIPS \
	| CECS_PLATFORM_MASK_SUPERH \
	| CECS_PLATFORM_MASK_POWERPC \
	| CECS_PLATFORM_MASK_SPARC \
	| CECS_PLATFORM_MASK_M68K \
)
#define CECS_PLATFORM_WORD_BITS CECS_PLATFORM_WORD_BITS_32
#define CECS_PLATFORM_WORD_BITS_LOG2 5
#else
#error "unable to determine platform word size, please define CECS_PLATFORM_WORD_BITS to the appropriate value for your platform (e.g. CECS_PLATFORM_WORD_BITS_32 or CECS_PLATFORM_WORD_BITS_64)"
// #define CECS_PLATFORM_WORD_BITS CECS_PLATFORM_WORD_BITS_32

#endif
#endif

#ifndef CECS_PLATFORM_WORD_BYTES
#define CECS_PLATFORM_WORD_BYTES (CECS_PLATFORM_WORD_BITS >> 3)
#endif


#ifndef CECS_PLATFORM_IS_64_BIT
#define CECS_PLATFORM_IS_64_BIT (CECS_PLATFORM_WORD_BITS == CECS_PLATFORM_WORD_BITS_64)
#endif
#ifndef CECS_PLATFORM_IS_32_BIT
#define CECS_PLATFORM_IS_32_BIT (CECS_PLATFORM_WORD_BITS == CECS_PLATFORM_WORD_BITS_32)
#endif


#endif


#endif
